echo "======================================================"
echo "======================================================"
echo "======================================================"
echo "=              RUNNING DEBUGGER AS ROOT              ="
echo "=              If you see this message:              ="
echo "=    unable to read password: Input/output error     ="
echo "= execute any command as root in the vscode terminal ="
echo "=    enter your password and restart the debugger    ="
echo "=             LUCK AND COURAGE TO YOU <3             ="
echo "======================================================"
echo "======================================================"
echo "======================================================"
sudo /usr/bin/gdb "$@"